### ISSUE TITLE
Dit is te ver van de opdracht

### ISSUE THREAD

**Issue by actuallymentor** [RicoEnzoo/toetsweek#1]
Ik kan hier niet uit opmaken of je een grapje maakt of dat je kat over je toetsenbord heeft gelopen.

Bewijs graag dat je alles begrijpt door een nieuwe commit te toen waarin je potato.txt de content "ik snap het" geeft met de comment "42 is the answer".

**Comment by RicoEnzoo** [comment]
Gefixt*
